### PR TITLE
Update to include Elemental 4.0

### PR DESCRIPTION
**Pull request by obj63mc**
Elemental is now at v4.0.0 - if you try to upgrade with composer this will fail

### CODE REVIEW

**Comment by jsirish** [comment]
Thanks @obj63mc 

Like the blog PR, could you adjust to only require Elemental `^4.0@dev`? We'll be dropping support for 2 & 3 in the new major version.

**Comment by obj63mc** [comment]
Done and Done

**Comment by jsirish** [comment]
Same note as the blog PR, could you remove the vendor folder from the commit?

The changes you made to the End Date/Time look nice! We'll merge those in as well.

**Comment by obj63mc** [comment]
You are all set, sorry about that.

**Comment by jsirish** [comment]
merged. thanks again @obj63mc !

**Pull request merged**
